spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/every?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ${DB_LOCAL_PASSWD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false




  data:
    elasticsearch:
      cluster-nodes: localhost:9200

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.web : DEBUG
  org.springframework.web.socket : DEBUG
  org.apache.kafka: DEBUG
  org.springframework.kafka: DEBUG
github:
  api:
    token: ${GIT_TOKEN}
    event.topic: github-events
server:
  port: 9000
